  
CREATE  PROCEDURE CUR_TMP_MOVIDET_2                                            
 @VALNROFACTURA  varchar(255),    
  @NROMOVI   varchar(255)                                                
AS                          
                            
DECLARE @PROVEEDOR varchar(255)                                           
DECLARE @NROFACTURA  varchar(255)                         
DECLARE @PRODUCTO  varchar(255)     
DECLARE @CANTIDAD  INT    
DECLARE @SUBTOTBAS  numeric(12,4)      
DECLARE @FECHA DATETIME    
                                                       
DECLARE cClientes_1 CURSOR FOR                            
    
SELECT FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO, ISNULL(CANTIDAD,0), SUBTOTBAS FROM TMP_MOVIDET    
 WHERE [Nº FACTURA]=@VALNROFACTURA       
OPEN cClientes_1                                            
FETCH cClientes_1 INTO @FECHA,@PROVEEDOR,@NROFACTURA,@PRODUCTO,@CANTIDAD,@SUBTOTBAS                             
WHILE (@@FETCH_STATUS = 0 )                                            
                                            
BEGIN                                                          
      
      
    PRINT CONVERT(VARCHAR(50), @CANTIDAD)  
      
IF @PRODUCTO='84 OCTANOS'       
BEGIN      
INSERT INTO TMP_MOVIDET_2(FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO, CANTIDAD,NROMOVI)      
VALUES(@FECHA,@PROVEEDOR,@NROFACTURA,'01',@CANTIDAD,@NROMOVI)     
END        
      
IF @PRODUCTO='90 OCTANOS'       
BEGIN      
INSERT INTO TMP_MOVIDET_2(FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO, CANTIDAD,NROMOVI)      
VALUES(@FECHA,@PROVEEDOR,@NROFACTURA,'02',@CANTIDAD,@NROMOVI)     
END     
    
IF @PRODUCTO='97 OCTANOS'       
BEGIN      
INSERT INTO TMP_MOVIDET_2(FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO, CANTIDAD,NROMOVI)      
VALUES(@FECHA,@PROVEEDOR,@NROFACTURA,'03',@CANTIDAD,@NROMOVI)     
END      
    
IF @PRODUCTO='DIESEL B5'       
BEGIN      
INSERT INTO TMP_MOVIDET_2(FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO, CANTIDAD,NROMOVI)      
VALUES(@FECHA,@PROVEEDOR,@NROFACTURA,'04',@CANTIDAD,@NROMOVI)     
END      
    
    
IF @PRODUCTO='84 OCTANOS1'       
BEGIN      
  
  
IF @CANTIDAD=0   
BEGIN   
INSERT INTO TMP_MOVIDET_2(FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO,CANTIDAD, SUBTOTBAS,NROMOVI)      
VALUES(@FECHA,@PROVEEDOR,@NROFACTURA,'01',1,@SUBTOTBAS,@NROMOVI)     
END  
ELSE  
BEGIN  
INSERT INTO TMP_MOVIDET_2(FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO, SUBTOTBAS,NROMOVI)      
VALUES(@FECHA,@PROVEEDOR,@NROFACTURA,'01',@SUBTOTBAS,@NROMOVI)     
END  
  
  
END     
     
IF @PRODUCTO='90 OCTANOS1'       
BEGIN      
  
IF @CANTIDAD=0   
BEGIN   
INSERT INTO TMP_MOVIDET_2(FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO,CANTIDAD, SUBTOTBAS,NROMOVI)      
VALUES(@FECHA,@PROVEEDOR,@NROFACTURA,'02',1,@SUBTOTBAS,@NROMOVI)     
END  
ELSE  
BEGIN  
INSERT INTO TMP_MOVIDET_2(FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO, SUBTOTBAS,NROMOVI)      
VALUES(@FECHA,@PROVEEDOR,@NROFACTURA,'02',@SUBTOTBAS,@NROMOVI)     
END  
    
  
END    
    
IF @PRODUCTO='97 OCTANOS1'       
BEGIN      
  
IF @CANTIDAD=0   
BEGIN   
INSERT INTO TMP_MOVIDET_2(FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO,CANTIDAD, SUBTOTBAS,NROMOVI)      
VALUES(@FECHA,@PROVEEDOR,@NROFACTURA,'03',1,@SUBTOTBAS,@NROMOVI)   
END  
ELSE  
BEGIN  
INSERT INTO TMP_MOVIDET_2(FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO, SUBTOTBAS,NROMOVI)      
VALUES(@FECHA,@PROVEEDOR,@NROFACTURA,'03',@SUBTOTBAS,@NROMOVI)   
END  
  
  
    
END      
    
IF @PRODUCTO='DIESEL B51'       
BEGIN      
  
IF @CANTIDAD=0   
BEGIN   
INSERT INTO TMP_MOVIDET_2(FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO,CANTIDAD, SUBTOTBAS,NROMOVI)      
VALUES(@FECHA,@PROVEEDOR,@NROFACTURA,'04',1,@SUBTOTBAS,@NROMOVI)     
END  
ELSE  
BEGIN  
INSERT INTO TMP_MOVIDET_2(FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO, SUBTOTBAS,NROMOVI)      
VALUES(@FECHA,@PROVEEDOR,@NROFACTURA,'04',@SUBTOTBAS,@NROMOVI)     
END  
  
END      
     
    
IF @PRODUCTO='FISE'       
BEGIN      
INSERT INTO TMP_MOVIDET_2(FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO,CANTIDAD, SUBTOTBAS,NROMOVI)      
VALUES(@FECHA,@PROVEEDOR,@NROFACTURA,'06',1,@SUBTOTBAS,@NROMOVI)     END      
    
IF @PRODUCTO='FISE1'       
BEGIN      
INSERT INTO TMP_MOVIDET_2(FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO,CANTIDAD, SUBTOTBAS,NROMOVI)      
VALUES(@FECHA,@PROVEEDOR,@NROFACTURA,'06',1,@SUBTOTBAS,@NROMOVI)     
END      
    
IF @PRODUCTO='FISE2'       
BEGIN      
INSERT INTO TMP_MOVIDET_2(FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO,CANTIDAD, SUBTOTBAS,NROMOVI)      
VALUES(@FECHA,@PROVEEDOR,@NROFACTURA,'06',1,@SUBTOTBAS,@NROMOVI)     
END      
    
IF @PRODUCTO='FISE3'       
BEGIN      
INSERT INTO TMP_MOVIDET_2(FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO,CANTIDAD, SUBTOTBAS,NROMOVI)      
VALUES(@FECHA,@PROVEEDOR,@NROFACTURA,'06',1,@SUBTOTBAS,@NROMOVI)     
END      
           
           
          
FETCH cClientes_1 INTO @FECHA,@PROVEEDOR,@NROFACTURA,@PRODUCTO,@CANTIDAD,@SUBTOTBAS                                             
END                                            
                                            
-- Cierre del cursor                                                                              
CLOSE cClientes_1                                            
                                            
-- Liberar los recursos                                                    
DEALLOCATE cClientes_1 