CREATE PROC SP_INSERT_TMP_MOVIDET  
  
AS  
DELETE FROM TMP_MOVIDET  
  
INSERT INTO TMP_MOVIDET(FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO,CANTIDAD)  
select FECHA,[PROVEEDOR],[Nº FACTURA] ,PRODUCTO,CANTIDAD     
FROM      
(SELECT FECHA,[PROVEEDOR],[Nº FACTURA],      
[84 OCTANOS],[90 OCTANOS],[97 OCTANOS],[DIESEL B5]              
   FROM Migrar       
) P      
UNPIVOT (CANTIDAD FOR PRODUCTO IN (      
[84 OCTANOS],[90 OCTANOS],[97 OCTANOS],[DIESEL B5]       
)) AS Unpvt      
WHERE CANTIDAD<>0    
  
  
INSERT INTO TMP_MOVIDET(FECHA,PROVEEDOR, [Nº FACTURA], PRODUCTO,  SUBTOTBAS)  
  
select FECHA,[PROVEEDOR],[Nº FACTURA] ,PRODUCTO,SUBTOTAL         
FROM      
(SELECT FECHA,[PROVEEDOR],[Nº FACTURA],      
[84 OCTANOS1],[FISE],[90 OCTANOS1],[FISE1],[97 OCTANOS1],[FISE2],[DIESEL B51],[FISE3]               
   FROM Migrar      
) P      
UNPIVOT (SUBTOTAL FOR PRODUCTO IN (      
[84 OCTANOS1],[FISE],[90 OCTANOS1],[FISE1],[97 OCTANOS1],[FISE2],[DIESEL B51],[FISE3]       
)) AS Unpvt      
WHERE SUBTOTAL<>0      